[database]
file = "./vzdv_data.sqlite"
resource_category_ordering = ["General", "SOP", "LOA", "Misc"]

[staff]
email_domain = "zdvartcc.org"
overrides = [
  { role = "FE", cid = 967658 },
  { role = "EC", cid = 1520736 }
]

[vatsim]
# This data is for the _dev_ SSO site
vatusa_api_key = ""
oauth_url_base = "https://auth-dev.vatsim.net/"
oauth_client_id = "225"
oauth_client_secret = "D3vUzNSt7HbhdaRYlIcBkBznBoh0JjTHAYHrOrn9"
oauth_client_callback_url = "http://localhost:3000/auth/callback"

[training]
certifications = [
  "GC T2 EGE",
  "GC T2 ASE",
  "GC T1",
  "LC T2 EGE",
  "LC T2 ASE",
  "LC T1",
  "APP T2 GJT",
  "APP T2 ASE",
  "APP T1",
  "ENR T2 ",
]

[airports]
all = [
  { code = "KANW", name = "Ainsworth Rgnl", location = "Ainsworth, NE", towered = false, class = "" },
  { code = "KAIA", name = "Alliance Muni", location = "Alliance, NE", towered = false, class = "" },
  { code = "KASE", name = "Aspen-pitkin County/sardy Fld", location = "Aspen, CO", towered = true, class = "D" },
  { code = "KRCV", name = "Astronaut Kent Rominger", location = "Del Norte, CO", towered = false, class = "" },
  { code = "KADT", name = "Atwood-rawlins County City-county", location = "Atwood, KS", towered = false, class = "" },
  { code = "KEFC", name = "Belle Fourche Muni", location = "Belle Fourche, SD", towered = false, class = "" },
  { code = "KCNP", name = "Billy G Ray Fld", location = "Chappell, NE", towered = false, class = "" },
  { code = "KSPF", name = "Black Hills-clyde Ice Fld", location = "Spearfish, SD", towered = false, class = "" },
  { code = "KAJZ", name = "Blake Fld", location = "Delta, CO", towered = false, class = "" },
  { code = "KBDG", name = "Blanding Muni", location = "Blanding, UT", towered = false, class = "" },
  { code = "KBDU", name = "Boulder Muni", location = "Boulder, CO", towered = false, class = "" },
  { code = "KHDE", name = "Brewster Fld", location = "Holdrege, NE", towered = false, class = "" },
  { code = "KBBW", name = "Broken Bow Muni/keith Glaze Fld", location = "Broken Bow, NE", towered = false, class = "" },
  { code = "KBKF", name = "Buckley Space Force Base", location = "Aurora, CO", towered = true, class = "D" },
  { code = "KFCS", name = "Butts AAF (Fort Carson)", location = "Fort Carson, CO", towered = true, class = "D" },
  { code = "KCSB", name = "Cambridge Muni", location = "Cambridge, NE", towered = false, class = "" },
  { code = "KGUR", name = "Camp Guernsey", location = "Guernsey, WY", towered = true, class = "D" },
  { code = "KCNY", name = "Canyonlands Rgnl", location = "Moab, UT", towered = false, class = "" },
  { code = "KCPR", name = "Casper/natrona County Intl", location = "Casper, WY", towered = true, class = "D" },
  { code = "KAPA", name = "Centennial", location = "Denver, CO", towered = true, class = "D" },
  { code = "KAEJ", name = "Central Colorado Rgnl", location = "Buena Vista, CO", towered = false, class = "" },
  { code = "KCDR", name = "Chadron Muni", location = "Chadron, NE", towered = false, class = "" },
  { code = "KSYF", name = "Cheyenne County Muni", location = "St Francis, KS", towered = false, class = "" },
  { code = "KCQJ", name = "Cheyenne Mtn Sfs", location = "Colorado Springs, CO", towered = false, class = "" },
  { code = "KCYS", name = "Cheyenne Rgnl/jerry Olson Fld", location = "Cheyenne, WY", towered = true, class = "D" },
  { code = "KCOS", name = "City Of Colorado Springs Muni", location = "Colorado Springs, CO", towered = true, class = "C" },
  { code = "KCFO", name = "Colorado Air And Space Port", location = "Denver, CO", towered = true, class = "D" },
  { code = "KAKO", name = "Colorado Plains Rgnl", location = "Akron, CO", towered = false, class = "" },
  { code = "KDGW", name = "Converse County", location = "Douglas, WY", towered = false, class = "" },
  { code = "KCEZ", name = "Cortez Muni", location = "Cortez, CO", towered = false, class = "" },
  { code = "KCZD", name = "Cozad Muni", location = "Cozad, NE", towered = false, class = "" },
  { code = "KCAG", name = "Craig-moffat", location = "Craig, CO", towered = false, class = "" },
  { code = "KBUB", name = "Cram Fld", location = "Burwell, NE", towered = false, class = "" },
  { code = "KCUT", name = "Custer County", location = "Custer, SD", towered = false, class = "" },
  { code = "KDEN", name = "Denver Intl", location = "Denver, CO", towered = true, class = "B" },
  { code = "KDWX", name = "Dixon", location = "Dixon, WY", towered = false, class = "" },
  { code = "KDRO", name = "Durango-la Plata County", location = "Durango, CO", towered = false, class = "" },
  { code = "KEGE", name = "Eagle County Rgnl", location = "Eagle, CO", towered = true, class = "D" },
  { code = "KRCA", name = "Ellsworth AFB", location = "Rapid City, SD", towered = true, class = "D" },
  { code = "KEIK", name = "Erie Muni", location = "Erie, CO", towered = false, class = "" },
  { code = "KFMM", name = "Fort Morgan Muni", location = "Fort Morgan, CO", towered = false, class = "" },
  { code = "KFMN", name = "Four Corners Rgnl", location = "Farmington, NM", towered = true, class = "D" },
  { code = "KFEW", name = "Francis E Warren AFB", location = "Cheyenne, WY", towered = false, class = "" },
  { code = "KOKS", name = "Garden County/king Rhiley Fld", location = "Oshkosh, NE", towered = false, class = "" },
  { code = "KGWS", name = "Glenwood Springs Muni", location = "Glenwood Springs, CO", towered = false, class = "" },
  { code = "KGRN", name = "Gordon Muni", location = "Gordon, NE", towered = false, class = "" },
  { code = "KGTE", name = "Gothenburg Muni", location = "Gothenburg, NE", towered = false, class = "" },
  { code = "KGNB", name = "Granby-grand County", location = "Granby, CO", towered = false, class = "" },
  { code = "KGJT", name = "Grand Junction Rgnl", location = "Grand Junction, CO", towered = true, class = "D" },
  { code = "KGGF", name = "Grant Muni", location = "Grant, NE", towered = false, class = "" },
  { code = "KGXY", name = "Greeley-weld County", location = "Greeley, CO", towered = false, class = "" },
  { code = "KGUC", name = "Gunnison-crested Butte Rgnl", location = "Gunnison, CO", towered = false, class = "" },
  { code = "KHAD", name = "Harford Fld", location = "Casper, WY", towered = false, class = "" },
  { code = "KHLC", name = "Hill City Muni", location = "Hill City, KS", towered = false, class = "" },
  { code = "KHEQ", name = "Holyoke", location = "Holyoke, CO", towered = false, class = "" },
  { code = "KAIB", name = "Hopkins Fld", location = "Nucla, CO", towered = false, class = "" },
  { code = "KHSR", name = "Hot Springs Muni", location = "Hot Springs, SD", towered = false, class = "" },
  { code = "KIML", name = "Imperial Muni", location = "Imperial, NE", towered = false, class = "" },
  { code = "KLXN", name = "Jim Kelly Fld", location = "Lexington, NE", towered = false, class = "" },
  { code = "KIBM", name = "Kimball Muni/robert E Arraj Fld", location = "Kimball, NE", towered = false, class = "" },
  { code = "KITR", name = "Kit Carson County", location = "Burlington, CO", towered = false, class = "" },
  { code = "KLHX", name = "La Junta Muni", location = "La Junta, CO", towered = false, class = "" },
  { code = "KLXV", name = "Lake County", location = "Leadville, CO", towered = false, class = "" },
  { code = "KLAR", name = "Laramie Rgnl", location = "Laramie, WY", towered = false, class = "" },
  { code = "KLIC", name = "Limon Muni", location = "Limon, CO", towered = false, class = "" },
  { code = "KLSK", name = "Lusk Muni", location = "Lusk, WY", towered = false, class = "" },
  { code = "KMCK", name = "Mc Cook Ben Nelson Rgnl", location = "Mc Cook, NE", towered = false, class = "" },
  { code = "KFLY", name = "Meadow Lake", location = "Colorado Springs, CO", towered = false, class = "" },
  { code = "KEEO", name = "Meeker Coulter Fld", location = "Meeker, CO", towered = false, class = "" },
  { code = "KVTN", name = "Miller Fld", location = "Valentine, NE", towered = false, class = "" },
  { code = "KECS", name = "Mondell Fld", location = "Newcastle, WY", towered = false, class = "" },
  { code = "KMVI", name = "Monte Vista Muni", location = "Monte Vista, CO", towered = false, class = "" },
  { code = "KMTJ", name = "Montrose Rgnl", location = "Montrose, CO", towered = false, class = "" },
  { code = "KLBF", name = "North Platte Rgnl/lee Bird Fld", location = "North Platte, NE", towered = false, class = "" },
  { code = "KGCC", name = "Northeast Wyoming Rgnl", location = "Gillette, WY", towered = false, class = "" },
  { code = "KFNL", name = "Northern Colorado Rgnl", location = "Fort Collins/loveland, CO", towered = true, class = "D" },
  { code = "KNRN", name = "Norton Muni", location = "Norton, KS", towered = false, class = "" },
  { code = "KOEL", name = "Oakley Muni", location = "Oakley, KS", towered = false, class = "" },
  { code = "KOIN", name = "Oberlin Muni", location = "Oberlin, KS", towered = false, class = "" },
  { code = "KPGA", name = "Page Muni", location = "Page, AZ", towered = false, class = "" },
  { code = "KTAD", name = "Perry Stokes", location = "Trinidad, CO", towered = false, class = "" },
  { code = "KEAN", name = "Phifer Airfield", location = "Wheatland, WY", towered = false, class = "" },
  { code = "KPHP", name = "Philip", location = "Philip, SD", towered = false, class = "" },
  { code = "KPHG", name = "Phillipsburg Muni", location = "Phillipsburg, KS", towered = false, class = "" },
  { code = "KIEN", name = "Pine Ridge", location = "Pine Ridge, SD", towered = false, class = "" },
  { code = "KPUB", name = "Pueblo Meml", location = "Pueblo, CO", towered = true, class = "D" },
  { code = "KRAP", name = "Rapid City Rgnl", location = "Rapid City, SD", towered = true, class = "D" },
  { code = "KRWL", name = "Rawlins Muni/harvey Fld", location = "Rawlins, WY", towered = false, class = "" },
  { code = "KGLD", name = "Renner Fld/goodland Muni", location = "Goodland, KS", towered = false, class = "" },
  { code = "KRIL", name = "Rifle Garfield County", location = "Rifle, CO", towered = false, class = "" },
  { code = "KRBE", name = "Rock County", location = "Bassett, NE", towered = false, class = "" },
  { code = "KBJC", name = "Rocky Mountain Metro", location = "Denver, CO", towered = true, class = "D" },
  { code = "KRCP", name = "Rooks County Rgnl", location = "Stockton, KS", towered = false, class = "" },
  { code = "KSUO", name = "Rosebud Sioux Tribal", location = "Rosebud, SD", towered = false, class = "" },
  { code = "KANK", name = "Salida/harriett Alexander Fld", location = "Salida, CO", towered = false, class = "" },
  { code = "KALS", name = "San Luis Valley Rgnl/bergman Fld", location = "Alamosa, CO", towered = false, class = "" },
  { code = "KTQK", name = "Scott City Muni", location = "Scott City, KS", towered = false, class = "" },
  { code = "KOGA", name = "Searle Fld", location = "Ogallala, NE", towered = false, class = "" },
  { code = "KCBK", name = "Shalz Fld", location = "Colby, KS", towered = false, class = "" },
  { code = "KSAA", name = "Shively Fld", location = "Saratoga, WY", towered = false, class = "" },
  { code = "KSNY", name = "Sidney Muni/lloyd W Carr Fld", location = "Sidney, NE", towered = false, class = "" },
  { code = "KLAA", name = "Southeast Colorado Rgnl", location = "Lamar, CO", towered = false, class = "" },
  { code = "KSBS", name = "Steamboat Springs/bob Adams Fld", location = "Steamboat Springs, CO", towered = false, class = "" },
  { code = "KSTK", name = "Sterling Muni", location = "Sterling, CO", towered = false, class = "" },
  { code = "KPSO", name = "Stevens Fld", location = "Pagosa Springs, CO", towered = false, class = "" },
  { code = "KTEX", name = "Telluride Rgnl", location = "Telluride, CO", towered = false, class = "" },
  { code = "KTIF", name = "Thomas County", location = "Thedford, NE", towered = false, class = "" },
  { code = "KTOR", name = "Torrington Muni", location = "Torrington, WY", towered = false, class = "" },
  { code = "KAFF", name = "Usaf Academy Airfield", location = "Colorado Springs, CO", towered = true, class = "D" },
  { code = "KLMO", name = "Vance Brand", location = "Longmont, CO", towered = false, class = "" },
  { code = "KBFF", name = "Western Nebraska Rgnl/william B Heilig Fld", location = "Scottsbluff, NE", towered = false, class = "" },
  { code = "KHDN", name = "Yampa Valley", location = "Hayden, CO", towered = false, class = "" },
]
weather_for = [
  "KDEN",
  "KCOS",
  "KASE",
  "KPUB",
  "KAPA"
]

[stats]
position_prefixes = ["APA", "ASE", "BKF", "BJC", "CFO", "COS", "CPR", "CYS", "DEN", "EGE", "FMN", "FNL", "GJT", "GUR", "PUB", "RAP", "RCA"]
position_suffixes = ["_RMP", "_DEL", "_GND", "_TWR", "_APP", "_DEP", "_CTR", "_RDO", "_FSS", "_OCA", "_TMU", "_FMP"]

[discord]
join_link = ""
bot_token = ""
guild_id = 0
online_channel = 0
# online_message = 0

[discord.webhooks]
staffing_request = ""
feedback = ""
new_visitor_app = ""

[discord.roles]
# role
guest = ""
controller_otm = ""
visiting_controller = ""
neighboring_controller = ""

# staff
sr_staff = ""
jr_staff = ""
vatusa_vatgov_staff = ""

# staff teams
training_staff = ""
event_team = ""
fe_team = ""
web_team = ""
ace_team = ""

# ratings
administrator = ""
supervisor = ""
instructor_3 = ""
instructor_1 = ""
controller_3 = ""
controller_1 = ""
student_3 = ""
student_2 = ""
student_1 = ""
observer = ""

[email]
host = "smtp.gmail.com"
port = 587
user = ""
password = ""
from = ""
reply_to = ""

[email.visitor_accepted_template]
subject = "You have been added to the visiting controller roster"
body = ""

[email.visitor_denied_template]
subject = "Your visiting controller request has been rejected"
body = ""

[email.visitor_removed_template]
subject = "You have been removed from the visiting controller roster"
body = ""
