[database]
file = "./vzdv_data.sqlite"
resource_category_ordering = []

[staff]
email_domain = ""
overrides = []

[vatsim]
vatusa_api_key = ""
oauth_url_base = ""
oauth_client_id = ""
oauth_client_secret = ""
oauth_client_callback_url = ""

[training]
certifications = []

[airports]
all = []
weather_for = []

[stats]
position_prefixes = []
position_suffixes = []

[discord]
join_link = ""
bot_token = ""
guild_id = 0
online_channel = 0
# online_message = 0
off_roster_channel = 0
owner_id = 0

[discord.auth]
client_id = ""
client_secret = ""
redirect_uri = ""

[discord.webhooks]
staffing_request = ""
feedback = ""
new_visitor_app = ""
errors = ""

[discord.roles]
# role
guest = 0
controller_otm = 0
visiting_controller = 0
neighboring_controller = 0

# staff
sr_staff = 0
jr_staff = 0
vatusa_vatgov_staff = 0

# staff teams
training_staff = 0
event_team = 0
fe_team = 0
web_team = 0
ace_team = 0

# ratings
administrator = 0
supervisor = 0
instructor_3 = 0
instructor_1 = 0
controller_3 = 0
controller_1 = 0
student_3 = 0
student_2 = 0
student_1 = 0
observer = 0

[email]
host = ""
port = 0
user = ""
password = ""
from = ""
reply_to = ""

[email.visitor_accepted_template]
subject = ""
body = ""

[email.visitor_denied_template]
subject = ""
body = ""

[email.visitor_removed_template]
subject = ""
body = ""

